### ISSUE TITLE
Not perfect

### ISSUE THREAD

**Issue by DiegoAsterio** [dosyago-coder-0/mimic-bloomberg-menu-no-js#4]
When you click with the left button over a topic and keep on navigating your copy differs slightly from the original. 
Watch the bloomberg site: 
![screenshot from 2018-06-27 12 12 14](https://user-images.githubusercontent.com/15999101/41968126-fd9fde0a-79f2-11e8-8347-dfc58c675f1a.png)
Watch yours:
![screenshot from 2018-06-27 12 13 37](https://user-images.githubusercontent.com/15999101/41968135-07f9a9c6-79f3-11e8-941a-696728ef00e5.png)
Two ticks are marked.

**Comment by dosyago-coder-0** [comment]
I'm okay with this actually. That's one reason.

Another reason is the function is actually slightly different from Bloomberg as well, to illustrate the menu concept.

On their site, clicking a section link in the left column actually causes a page navigation, but in my copy, clicking that link just locks the right panel for that section in place. This displays a useful functionality of the menu concept that their site does not.

Like I said, I prefer that. 

Closes #4
